apiVersion: v1
kind: ConfigMap
metadata:
  name: marketing-html
  namespace: default
data:
  index.html: |
    <html>
      <body style="background-color: #282c34; color: white; font-family: sans-serif; text-align: center; padding-top: 50px;">
        <h1>Customer 0 Sandbox: Marketing Site</h1>
        <p>Status: <b>Nginx Ingress Validated</b></p>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketing-site
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marketing
  template:
    metadata:
      labels:
        app: marketing
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: marketing-html
---
apiVersion: v1
kind: Service
metadata:
  name: marketing-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: marketing